[2,"\n"]
[1,"Rendering:\n"]
[1,"ERROR: The process cannot access the file because it is being used by another process. (os error 32): remove 'C:\\Users\\Data Analyst QuinCTY\\Documents\\One Drive Only\\Github\\CHA\\html_outputs'\n\nStack trace:\n    at Object.removeSync (ext:deno_fs/30_fs.js:250:3)\n    at removeIfExists (file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:4756:14)\n    at renderProject (file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:78414:17)\n    at eventLoopTick (ext:core/01_core.js:153:7)\n    at async serveProject (file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:100122:24)\n    at async Command.actionHandler (file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:100815:9)\n    at async Command.execute (file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:8017:13)\n    at async Command.parseCommand (file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:7907:20)\n    at async quarto (file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:118224:9)\n    at async file:///C:/Users/DATAAN~1/AppData/Local/Programs/Quarto/bin/quarto.js:118244:9\n"]
